// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaveEnterprise.Data;

#nullable disable

namespace RaveEnterprise.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230331222338_SeedRaveTable")]
    partial class SeedRaveTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaveEnterprise.Models.Rave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Raves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Net Core",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " It has a strong resemblance with Java, it has numerous strong programming features that make it endearing to a number of programmers worldwide. Following is the list of a few important features ",
                            Name = "Core Purple Boot",
                            PictureUrl = "https://www.pexels.com/photo/white-concrete-2-storey-house-206172/",
                            Price = 17990L,
                            QuantityInStock = 100,
                            Type = "Boot",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Net Core",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "There are no prerequisites required to learn C#.NET as we are going to start from the very basics. It is good to have .NET Framework and Visual Studio installed on your computer, as it might assist you in executing the examples yourself and getting to know how it works.",
                            Name = "Core Purple Boot",
                            PictureUrl = "https://www.pexels.com/photo/palm-trees-at-night-258154/",
                            Price = 17990L,
                            QuantityInStock = 100,
                            Type = "Boot",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Redis",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Core I5 16gb RAM 256gb SSD 10th Generation 14inch Screen",
                            Name = "Core Red Boot",
                            PictureUrl = "https://www.pexels.com/photo/white-concrete-2-storey-house-206172/",
                            Price = 18999L,
                            QuantityInStock = 100,
                            Type = "Boot",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Net Core",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " It has a strong resemblance with Java, it has numerous strong programming features that make it endearing to a number of programmers worldwide. Following is the list of a few important features ",
                            Name = "Core Purple Boot",
                            PictureUrl = "https://www.pexels.com/photo/palm-trees-at-night-258154/",
                            Price = 17990L,
                            QuantityInStock = 100,
                            Type = "Boot",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Brand = "DELL G5",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "There are no prerequisites required to learn C#.NET as we are going to start from the very basics. It is good to have .NET Framework and Visual Studio installed on your computer, as it might assist you in executing the examples yourself and getting to know how it works.",
                            Name = "Angular Blue Boot",
                            PictureUrl = "https://www.pexels.com/photo/construction-house-architecture-luxury-53610/",
                            Price = 430000L,
                            QuantityInStock = 100,
                            Type = "Angular",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Net Core",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Running as admin worked for me after experiencing the same issue.",
                            Name = "Core Purple Boot",
                            PictureUrl = "https://www.pexels.com/photo/construction-house-architecture-luxury-53610/",
                            Price = 17990L,
                            QuantityInStock = 100,
                            Type = "Boot",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Brand = "DELL G5",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Core I5 16gb RAM 256gb SSD 10th Generation 14inch Screen",
                            Name = "Angular Blue Boot",
                            PictureUrl = "https://www.pexels.com/photo/architecture-beach-blue-chairs-261101/",
                            Price = 430000L,
                            QuantityInStock = 100,
                            Type = "Angular",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Net Core",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Running as admin worked for me after experiencing the same issue.",
                            Name = "Core Purple Boot",
                            PictureUrl = "https://www.pexels.com/photo/architecture-beach-blue-chairs-261101/",
                            Price = 17990L,
                            QuantityInStock = 100,
                            Type = "Boot",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Net Core",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Running as admin worked for me after experiencing the same issue.",
                            Name = "Core Purple Boot",
                            PictureUrl = "https://www.pexels.com/photo/construction-house-architecture-luxury-53610/",
                            Price = 17990L,
                            QuantityInStock = 100,
                            Type = "Boot",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Net Core",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "There are no prerequisites required to learn C#.NET as we are going to start from the very basics. It is good to have .NET Framework and Visual Studio installed on your computer, as it might assist you in executing the examples yourself and getting to know how it works.",
                            Name = "Core Purple Boot",
                            PictureUrl = "https://www.pexels.com/photo/architecture-beach-blue-chairs-261101/",
                            Price = 17990L,
                            QuantityInStock = 100,
                            Type = "Boot",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
